### ISSUE TITLE
Add support to publish test report to gh pages

### ISSUE THREAD

**Issue by st1p3kolovrat** [cybersokari/allure-report-deployer#17]
**Is your feature request related to a problem? Please describe.**
Now we can publish test report to firebase. If we want to keep things private it would be awesome to have ability to publish test report to gh pages instead of firebase

**Comment by cybersokari** [comment]
@st1p3kolovrat Thank you for raising this issue and pointing out the functionality differences.

[simple-elf/allure-report-action](https://github.com/simple-elf/allure-report-action) focuses on generating reports with history, but it doesn’t handle deployment to GitHub pages. To deploy the generated report to GitHub Pages, you would need an additional action like [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) or similar.

Rather than integrating a specific GitHub Pages deployment feature into this project, I propose exposing the generated test report in the `allure_report` directory while making deployment to Firebase optional. This approach would allow users to seamlessly integrate their preferred deployment actions, such as [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages), into their workflows.

Even without a Firebase deployment feature, the ability to generate test reports with History and Retries without committing files to Git still makes this project highly valuable. I believe this is a flexible and user-centric step forward.

Would you be open to testing a draft implementation where the `allure_report` directory is exposed? Your feedback would be greatly appreciated and instrumental in refining this feature. Let me know your thoughts!

**Comment by st1p3kolovrat** [comment]
Im not following you intention with what you mean on allure_report exposed. Can you elaborate? 

I would be able to test after you have done preliminary testing and you have good faith that it is looking good. Goal would be to have test report not use firebase but generate test report in gh pages. This would make it private, while firebase url is public

**Comment by cybersokari** [comment]
@st1p3kolovrat The latest version of the GitHub action now supports GitHub pages.  

Here's an example [test run](https://github.com/cybersokari/allure-report-deployer/actions/runs/12770263352) and [workflow](https://github.com/cybersokari/allure-report-deployer/actions/runs/12770263352/workflow) for your convenience.

I also updated the documentation to reflect the new feature. Feel free to leave a comment if you have any questions.

**Comment by st1p3kolovrat** [comment]
Seems like you had a few version updates since your last post. 

I have finally took the time to test your implementation. It seems that I am not getting the expected test report url in the `summary`. 

Now I am not sure if I am missing something, therefore your advice is welcomed. 

This is the summary of the test run: 
![Image](https://github.com/user-attachments/assets/a7995e46-6d55-43c0-8261-8f9d44b9303f)

This is the snippet of the workflow: 
```
name: Run API Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

...

      - name: Generate Test Report
        if: always()
        uses: cybersokari/allure-deployer-action@v1.7.6
        with:
          target: 'github'
          github_pages_branch: 'gh-pages-tests'
          allure_results_path: 'tests/allure-results'
          google_credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
          github_token: ${{ secrets.PAT_TOKEN }}
```
